In [1]:
from model_hetero import *
import numpy as np
import pandas as pd

### Heterogeneous Groups

In [2]:
vo =0.5
vn=0.7
𝜌L=1
𝜌H=1
σo=0.5
σn=0.7
𝛿o=0.5
𝛿n=0.7
I=0.01
𝛼=0.0138
𝛽H=14*2.4/18
𝛽L=0.1 * 𝛽H
m_vals=np.linspace(0.1,0.8,71)

param=map(lambda m: GRBT_Hetero(m,I_0=I,𝜌L=𝜌L,𝜌H=𝜌H,σo=σo,σn=σn,δo=δo,δn=δn,vo=vo,vn=vn,𝛽L=𝛽L,𝛽H=𝛽H),m_vals)
paramdata= pd.DataFrame.from_records(list(param), columns =['m','p','q','ICphi','ICn',
                                                            'πB','πA','πA0','πB0','πA1','πB1',
                                                            'S3','I3','D_vals','Uphi','Un','Ud'])
paramdata.to_csv("210407 GRBT Hetero.csv")
paramdata

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_hetero.py:150: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nR,nD]))
C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_hetero.py:526: RuntimeWarning: divide by zero encountered in double_scalars
  πA0 = min(m/π2_0_coef,1)
C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_hetero.py:517: RuntimeWarning: divide by zero encountered in double_scalars
  πB = min(m/πB_coef,1)

,m,p,q,ICphi,ICn,πB,πA,πA0,πB0,πA1,πB1,S3,I3,D_vals,Uphi,Un,Ud
0,0.10,0.701740346161207,0,0.000000e+00,-0.113106,0.158349,0.000000,0.271455,0.0,0.000000,0.000000,0.985435,0.003064,0.000204,0.190018,1.390018,1.200000
1,0.11,0.7096249247968917,0,-5.551115e-17,-0.124417,0.174183,0.000000,0.298600,0.0,0.000000,0.000000,0.985382,0.003093,0.000204,0.209020,1.409020,1.200000
2,0.12,0.7176887012245123,0,5.551115e-17,-0.135727,0.190018,0.000000,0.325746,0.0,0.000000,0.000000,0.985334,0.003119,0.000205,0.228022,1.428022,1.200000
3,0.13,0.7259378546782733,0,-5.551115e-17,-0.147038,0.205853,0.000000,0.352891,0.0,0.000000,0.000000,0.985290,0.003140,0.000206,0.247024,1.447024,1.200000
4,0.14,0.7343788517986208,0,5.551115e-17,-0.158349,0.221688,0.000000,0.380037,0.0,0.000000,0.000000,0.985252,0.003157,0.000207,0.266026,1.466026,1.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,0.76,1,0,3.011669e-02,-0.195393,1.000000,0.684287,1.000000,1.0,1.000000,0.000411,0.985985,0.002508,0.000204,1.200082,2.036857,0.836775
67,0.77,1,0,1.303496e-02,-0.200269,1.000000,0.701375,1.000000,1.0,1.000000,0.000434,0.986007,0.002504,0.000204,1.200087,2.040275,0.840188
68,0.78,0,0,-2.944622e-03,-0.160045,1.000000,0.780059,1.000000,1.0,0.718097,0.000000,0.985881,0.002630,0.000206,1.202061,2.012032,0.809970
69,0.79,0,0,-1.580286e-02,-0.165760,1.000000,0.790060,1.000000,1.0,0.734324,0.000000,0.985911,0.002619,0.000206,1.211062,2.016032,0.804970
70,0.80,0,0,-2.866109e-02,-0.171475,1.000000,0.800061,1.000000,1.0,0.750145,0.000000,0.985941,0.002607,0.000206,1.220063,2.020032,0.799970

In [3]:
result=map(lambda x: SRA1_Hetero(x,I_0=I,σo=σo,σn=σn,δo=δo,δn=δn,𝛽L=𝛽L,𝛽H=𝛽H),m_vals)
result=list(result)
data=pd.DataFrame.from_records(result, columns =['func', 'π1','π2','Uphi','Un','Ud'])
data['m']=m_vals
data=data.rename(columns={'func':'D_vals'})


data.to_csv('210407 SRA1 Hetero.csv',index=False)
data

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_hetero.py:150: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nR,nD]))

      D_vals        π1        π2      Uphi        Un        Ud     m
0   0.000204  0.100008  0.100013  0.185017  1.335013  1.149996  0.10
1   0.000206  0.110008  0.110014  0.202969  1.347964  1.144996  0.11
2   0.000207  0.120009  0.120015  0.220820  1.360816  1.139995  0.12
3   0.000208  0.130010  0.130016  0.238572  1.373567  1.134995  0.13
4   0.000209  0.140011  0.140018  0.256223  1.386218  1.129995  0.14
..       ...       ...       ...       ...       ...       ...   ...
66  0.000209  0.760058  0.760096  1.155278  1.975249  0.819971  0.76
67  0.000209  0.770059  0.770097  1.166628  1.981599  0.814971  0.77
68  0.000209  0.780059  0.780099  1.177879  1.987849  0.809970  0.78
69  0.000208  0.790060  0.790100  1.189029  1.993999  0.804970  0.79
70  0.000208  0.800061  0.800101  1.200079  2.000049  0.799970  0.80

[71 rows x 7 columns]

In [4]:
result=map(lambda x: SRA2_Hetero(x,I_0=I,σo=σo,σn=σn,δo=δo,δn=δn,𝛽L=𝛽L,𝛽H=𝛽H),m_vals)
result=list(result)
data=pd.DataFrame.from_records(result, columns =['func', 'π1','π20','π21','Uphi','Un','Ud'])
data['m']=m_vals
data=data.rename(columns={'func':'D_vals'})


data.to_csv('210407 SRA2 Hetero.csv',index=False)
data

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_hetero.py:150: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nR,nD]))

      D_vals        π1       π20       π21      Uphi        Un        Ud     m
0   0.000204  0.100008  0.111126  0.000000  0.190018  1.340014  1.149996  0.10
1   0.000205  0.110008  0.123612  0.000000  0.209020  1.354016  1.144996  0.11
2   0.000206  0.120009  0.136382  0.000000  0.228022  1.368017  1.139995  0.12
3   0.000207  0.130010  0.149446  0.000000  0.247023  1.382018  1.134995  0.13
4   0.000208  0.140011  0.162813  0.000000  0.266025  1.396020  1.129995  0.14
..       ...       ...       ...       ...       ...       ...       ...   ...
66  0.000207  0.760058  1.000000  0.684361  1.184060  2.004031  0.819971  0.76
67  0.000207  0.770059  1.000000  0.701448  1.193060  2.008031  0.814971  0.77
68  0.000206  0.780059  1.000000  0.718097  1.202061  2.012032  0.809970  0.78
69  0.000206  0.790060  1.000000  0.734324  1.211062  2.016032  0.804970  0.79
70  0.000206  0.800061  1.000000  0.750145  1.220063  2.020032  0.799970  0.80

[71 rows x 8 columns]

### Heterogeneous Groups and Old Protection Rate 0.27

In [5]:
vo =0.5
vn=0.7
𝜌L=1
𝜌H=1
σo=0.27
σn=0.7
𝛿o=0.27
𝛿n=0.7
I=0.01
𝛼=0.0138
𝛽H=14*2.4/18
𝛽L=0.1 * 𝛽H
m_vals=np.linspace(0.1,0.8,71)

param=map(lambda m: GRBT_Hetero(m,I_0=I,𝜌L=𝜌L,𝜌H=𝜌H,σo=σo,σn=σn,δo=δo,δn=δn,vo=vo,vn=vn,𝛽L=𝛽L,𝛽H=𝛽H),m_vals)
paramdata= pd.DataFrame.from_records(list(param), columns =['m','p','q','ICphi','ICn',
                                                            'πB','πA','πA0','πB0','πA1','πB1',
                                                            'S3','I3','D_vals','Uphi','Un','Ud'])
paramdata.to_csv("210407 GRBT Hetero and old027.csv")
paramdata

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_hetero.py:150: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nR,nD]))
C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_hetero.py:526: RuntimeWarning: divide by zero encountered in double_scalars
  πA0 = min(m/π2_0_coef,1)
C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_hetero.py:517: RuntimeWarning: divide by zero encountered in double_scalars
  πB = min(m/πB_coef,1)

,m,p,q,ICphi,ICn,πB,πA,πA0,πB0,πA1,πB1,S3,I3,D_vals,Uphi,Un,Ud
0,0.10,0.701740346161207,0,0.000000e+00,-0.113106,0.158349,0.000000,0.271455,0.0,0.000000,0.000000,0.985023,0.003310,0.000209,0.190018,1.390018,1.200000
1,0.11,0.7096249247968917,0,-5.551115e-17,-0.124417,0.174183,0.000000,0.298600,0.0,0.000000,0.000000,0.984929,0.003364,0.000211,0.209020,1.409020,1.200000
2,0.12,0.7176887012245123,0,5.551115e-17,-0.135727,0.190018,0.000000,0.325746,0.0,0.000000,0.000000,0.984840,0.003414,0.000212,0.228022,1.428022,1.200000
3,0.13,0.7259378546782733,0,-5.551115e-17,-0.147038,0.205853,0.000000,0.352891,0.0,0.000000,0.000000,0.984757,0.003459,0.000214,0.247024,1.447024,1.200000
4,0.14,0.7343788517986208,0,5.551115e-17,-0.158349,0.221688,0.000000,0.380037,0.0,0.000000,0.000000,0.984679,0.003500,0.000215,0.266026,1.466026,1.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,0.76,1,0,3.011669e-02,-0.195393,1.000000,0.684287,1.000000,1.0,1.000000,0.000411,0.985360,0.002868,0.000214,1.200082,2.036857,0.836775
67,0.77,1,0,1.303496e-02,-0.200269,1.000000,0.701375,1.000000,1.0,1.000000,0.000434,0.985411,0.002847,0.000214,1.200087,2.040275,0.840188
68,0.78,0,0,-2.944622e-03,-0.160045,1.000000,0.780059,1.000000,1.0,0.718097,0.000000,0.985251,0.003074,0.000217,1.202061,2.012032,0.809970
69,0.79,0,0,-1.580286e-02,-0.165760,1.000000,0.790060,1.000000,1.0,0.734324,0.000000,0.985308,0.003043,0.000216,1.211062,2.016032,0.804970
70,0.80,0,0,-2.866109e-02,-0.171475,1.000000,0.800061,1.000000,1.0,0.750145,0.000000,0.985366,0.003012,0.000216,1.220063,2.020032,0.799970

In [6]:
result=map(lambda x: SRA1_Hetero(x,I_0=I,σo=σo,σn=σn,δo=δo,δn=δn,𝛽L=𝛽L,𝛽H=𝛽H),m_vals)
result=list(result)
data=pd.DataFrame.from_records(result, columns =['func', 'π1','π2','Uphi','Un','Ud'])
data['m']=m_vals
data=data.rename(columns={'func':'D_vals'})


data.to_csv('210407 SRA1 Hetero and old027.csv',index=False)
data

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_hetero.py:150: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nR,nD]))

      D_vals        π1        π2      Uphi        Un        Ud     m
0   0.000210  0.100008  0.100013  0.185017  1.335013  1.149996  0.10
1   0.000212  0.110008  0.110014  0.202969  1.347964  1.144996  0.11
2   0.000213  0.120009  0.120015  0.220820  1.360816  1.139995  0.12
3   0.000215  0.130010  0.130016  0.238572  1.373567  1.134995  0.13
4   0.000217  0.140011  0.140018  0.256223  1.386218  1.129995  0.14
..       ...       ...       ...       ...       ...       ...   ...
66  0.000221  0.760058  0.760096  1.155278  1.975249  0.819971  0.76
67  0.000220  0.770059  0.770097  1.166628  1.981599  0.814971  0.77
68  0.000219  0.780059  0.780099  1.177879  1.987849  0.809970  0.78
69  0.000218  0.790060  0.790100  1.189029  1.993999  0.804970  0.79
70  0.000217  0.800061  0.800101  1.200079  2.000049  0.799970  0.80

[71 rows x 7 columns]

In [7]:
result=map(lambda x: SRA2_Hetero(x,I_0=I,σo=σo,σn=σn,δo=δo,δn=δn,𝛽L=𝛽L,𝛽H=𝛽H),m_vals)
result=list(result)
data=pd.DataFrame.from_records(result, columns =['func', 'π1','π20','π21','Uphi','Un','Ud'])
data['m']=m_vals
data=data.rename(columns={'func':'D_vals'})


data.to_csv('210407 SRA2 Hetero and old027.csv',index=False)
data

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_hetero.py:150: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nR,nD]))

      D_vals        π1       π20       π21      Uphi        Un        Ud     m
0   0.000210  0.100008  0.111126  0.000000  0.190018  1.340014  1.149996  0.10
1   0.000212  0.110008  0.123612  0.000000  0.209020  1.354016  1.144996  0.11
2   0.000213  0.120009  0.136382  0.000000  0.228022  1.368017  1.139995  0.12
3   0.000215  0.130010  0.149446  0.000000  0.247023  1.382018  1.134995  0.13
4   0.000216  0.140011  0.162813  0.000000  0.266025  1.396020  1.129995  0.14
..       ...       ...       ...       ...       ...       ...       ...   ...
66  0.000218  0.760058  1.000000  0.684361  1.184060  2.004031  0.819971  0.76
67  0.000218  0.770059  1.000000  0.701448  1.193060  2.008031  0.814971  0.77
68  0.000217  0.780059  1.000000  0.718097  1.202061  2.012032  0.809970  0.78
69  0.000216  0.790060  1.000000  0.734324  1.211062  2.016032  0.804970  0.79
70  0.000216  0.800061  1.000000  0.750145  1.220063  2.020032  0.799970  0.80

[71 rows x 8 columns]