In [1]:
from model_quarantine import *
import numpy as np
import pandas as pd

In [2]:
vo =0.5
vn=0.7
𝜌 = 1
σo=0.5
σn=0.7
𝛿o=0.5
𝛿n=0.7
I=0.01
𝛼=0.0138
m_vals=np.linspace(0.1,0.8,71)

param=map(lambda m: GRBT_Qua(m,I_0=I,𝜌=𝜌,σo=σo,σn=σn,δo=δo,δn=δn,vo=vo,vn=vn),m_vals)
paramdata= pd.DataFrame.from_records(list(param), columns =['m','p','q','ICphi','ICn',
                                                            'πB','πA','πA0','πB0','πA1','πB1',
                                                            'S4','I4','D_vals','Uphi','Un','Ud'])
paramdata.to_csv('210407 GRBT quarantine.csv',index=False)
paramdata

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_quarantine.py:183: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nI_I,nR_I,nR,nD]))
C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_quarantine.py:1010: RuntimeWarning: divide by zero encountered in double_scalars
  πA0 = min(m/π2_0_coef,1)
C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_quarantine.py:1001: RuntimeWarning: divide by zero encountered in double_scalars
  πB = min(m/πB_coef,1)

,m,p,q,ICphi,ICn,πB,πA,πA0,πB0,πA1,πB1,S4,I4,D_vals,Uphi,Un,Ud
0,0.10,0.7013121204816467,0,1.110223e-16,-0.113277,0.158588,0.000000,0.271865,0.0,0.000000,0.000000,0.896007,0.062424,0.001935,0.190305,1.390305,1.200000
1,0.11,0.7092029863468372,0,0.000000e+00,-0.124603,0.174444,0.000000,0.299047,0.0,0.000000,0.000000,0.899954,0.059350,0.001860,0.209333,1.409333,1.200000
2,0.12,0.7172730629513923,0,1.110223e-16,-0.135928,0.190299,0.000000,0.326228,0.0,0.000000,0.000000,0.903762,0.056399,0.001788,0.228359,1.428359,1.200000
3,0.13,0.7255285299790578,0,1.110223e-16,-0.147253,0.206155,0.000000,0.353408,0.0,0.000000,0.000000,0.907436,0.053565,0.001718,0.247386,1.447386,1.200000
4,0.14,0.7339758545407306,0,-1.110223e-16,-0.158578,0.222009,0.000000,0.380587,0.0,0.000000,0.000000,0.910978,0.050846,0.001650,0.266411,1.466411,1.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,0.76,1,0,3.053014e-02,-0.194337,1.000000,0.685186,1.000000,1.0,1.000000,0.005006,0.983274,0.002604,0.000277,1.201001,2.037037,0.836036
67,0.77,1,0,1.352015e-02,-0.199141,1.000000,0.702274,1.000000,1.0,1.000000,0.005280,0.983467,0.002542,0.000274,1.201056,2.040455,0.839399
68,0.78,0,0,-3.996545e-03,-0.160596,1.000000,0.780761,1.000000,1.0,0.719921,0.000000,0.983287,0.002630,0.000277,1.202798,2.012417,0.809620
69,0.79,0,0,-1.686572e-02,-0.166315,1.000000,0.790771,1.000000,1.0,0.736122,0.000000,0.983516,0.002552,0.000273,1.211806,2.016421,0.804615
70,0.80,0,0,-2.973488e-02,-0.172035,1.000000,0.800780,1.000000,1.0,0.751918,0.000000,0.983739,0.002477,0.000269,1.220814,2.020424,0.799610

In [3]:
m_vals=np.linspace(0.1,0.8,71)
σo_set=0.5
σn_set=0.7

result=map(lambda x: SRA1_Qua(x,I_0=0.01,σo=σo_set,σn=σn_set),m_vals)
result=list(result)
data=pd.DataFrame.from_records(result, columns =['func', 'π1','π2','S3','I3','Uphi','Un','Ud'])
data['m']=m_vals
data=data.rename(columns={'func':'D_vals'})


data.to_csv('210407 SRA1 quarantine.csv',index=False)
data

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_quarantine.py:183: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nI_I,nR_I,nR,nD]))

,D_vals,π1,π2,S3,I3,Uphi,Un,Ud,m
0,0.001958,0.100098,0.100289,0.894809,0.063388,0.185300,1.335251,1.149951,0.10
1,0.001887,0.110107,0.110315,0.898553,0.060473,0.203276,1.348223,1.144946,0.11
2,0.001819,0.120117,0.120341,0.902153,0.057685,0.221152,1.361093,1.139941,0.12
3,0.001753,0.130127,0.130367,0.905612,0.055017,0.238927,1.373863,1.134937,0.13
4,0.001689,0.140137,0.140392,0.908935,0.052467,0.256601,1.386533,1.129932,0.14
...,...,...,...,...,...,...,...,...,...
66,0.000291,0.760741,0.761309,0.982585,0.003019,1.156226,1.975856,0.819629,0.76
67,0.000286,0.770751,0.771317,0.982854,0.002909,1.167576,1.982201,0.814624,0.77
68,0.000281,0.780761,0.781325,0.983113,0.002804,1.178827,1.988446,0.809620,0.78
69,0.000277,0.790771,0.791333,0.983364,0.002704,1.189976,1.994591,0.804615,0.79
70,0.000272,0.800780,0.801341,0.983606,0.002610,1.201026,2.000636,0.799610,0.80

In [4]:
m_vals=np.linspace(0.1,0.8,71)
σo_set=0.5
σn_set=0.7

result=map(lambda x: SRA2_Qua(x,I_0=0.01,σo=σo_set,σn=σn_set),m_vals)
result=list(result)
data=pd.DataFrame.from_records(result, columns =['func','π1','π20','π21','S3','I3','Uphi','Un','Ud'])
data['m']=m_vals
data=data.rename(columns={'func':'D_vals'})

data.to_csv('210407 SRA2 quarantine.csv',index=False)
data

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_quarantine.py:183: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nI_I,nR_I,nR,nD]))

,D_vals,π1,π20,π21,S3,I3,Uphi,Un,Ud,m
0,0.001945,0.100098,0.111444,0.000000,0.895452,0.062744,0.190319,1.340271,1.149951,0.10
1,0.001872,0.110107,0.123965,0.000000,0.899303,0.059724,0.209350,1.354296,1.144946,0.11
2,0.001801,0.120117,0.136770,0.000000,0.903011,0.056827,0.228379,1.368321,1.139941,0.12
3,0.001733,0.130127,0.149869,0.000000,0.906580,0.054049,0.247409,1.382345,1.134937,0.13
4,0.001667,0.140137,0.163272,0.000000,0.910015,0.051386,0.266438,1.396370,1.129932,0.14
...,...,...,...,...,...,...,...,...,...,...
66,0.000286,0.760741,1.000000,0.686239,0.982807,0.002796,1.184781,2.004410,0.819629,0.76
67,0.000282,0.770751,1.000000,0.703298,0.983051,0.002712,1.193789,2.008414,0.814624,0.77
68,0.000277,0.780761,1.000000,0.719921,0.983287,0.002630,1.202798,2.012417,0.809620,0.78
69,0.000273,0.790771,1.000000,0.736122,0.983516,0.002552,1.211806,2.016421,0.804615,0.79
70,0.000269,0.800780,1.000000,0.751918,0.983739,0.002477,1.220814,2.020424,0.799610,0.80