In [1]:
from model_TimeExt import *
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
vo =0.5
vn=0.7
𝜌 = 1
σo=0.5
σn=0.7
𝛿o=0.5
𝛿n=0.7
I=0.01
m_vals=np.linspace(0.1,0.8,71)

param=map(lambda m: GRBT_EXT(m,I_0=I,𝜌=𝜌,σo=σo,σn=σn,δo=δo,δn=δn,vo=vo,vn=vn),m_vals)
paramdata= pd.DataFrame.from_records(list(param), columns =['m','p','q','ICphi','ICn',
                                                            'πB','πA','πA0','πB0','πA1','πB1',
                                                            'πA00','πB00','πA01','πA10','πB01','πB10','πA11','πB11',
                                                            'S4','I4','D_vals','Ud'])
paramdata.to_csv('210407 GRBT TimeExtMaskExp.csv',index=False)
paramdata

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_TimeExt.py:216: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nR,nD]))

,m,p,q,ICphi,ICn,πB,πA,πA0,πB0,πA1,...,πA01,πA10,πB01,πB10,πA11,πB11,S4,I4,D_vals,Ud
0,0.10,0.5555285099018648,0,-7.993606e-15,-0.142873,0.200022,0.000000,0.200022,0.0,0,...,0.000000,0.000000,0.000000,0.000000,0,0,0.891244,0.066380,0.001795,1.200000
1,0.11,0.5617708253024285,0,1.076916e-14,-0.157160,0.220024,0.000000,0.220024,0.0,0,...,0.000000,0.000000,0.000000,0.000000,0,0,0.896136,0.062648,0.001713,1.200000
2,0.12,0.5681550070908775,0,6.550316e-15,-0.171447,0.240026,0.000000,0.240026,0.0,0,...,0.000000,0.000000,0.000000,0.000000,0,0,0.900821,0.059089,0.001635,1.200000
3,0.13,0.5746859472115999,0,9.103829e-15,-0.185734,0.260028,0.000000,0.260028,0.0,0,...,0.000000,0.000000,0.000000,0.000000,0,0,0.905305,0.055699,0.001560,1.200000
4,0.14,0.581368765141304,0,2.409184e-14,-0.200021,0.280030,0.000000,0.280030,0.0,0,...,0.000000,0.000000,0.000000,0.000000,0,0,0.909595,0.052470,0.001487,1.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,0.76,1,0,1.202347e-01,-0.105286,1.000000,0.684271,1.000000,1.0,1,...,0.760174,0.760174,0.760174,0.760174,0,0,0.983532,0.003760,0.000247,0.852679
67,0.77,1,0,9.827207e-02,-0.115043,1.000000,0.701359,1.000000,1.0,1,...,0.770176,0.770176,0.770176,0.770176,0,0,0.983690,0.003701,0.000244,0.847093
68,0.78,1,0,7.687311e-02,-0.124549,1.000000,0.718009,1.000000,1.0,1,...,0.780178,0.780178,0.780178,0.780178,0,0,0.983844,0.003644,0.000242,0.840996
69,0.79,1,0,5.601648e-02,-0.133814,1.000000,0.734237,1.000000,1.0,1,...,0.790180,0.790180,0.790180,0.790180,0,0,0.983995,0.003590,0.000239,0.832881
70,0.80,1,0,3.568197e-02,-0.142847,1.000000,0.750060,1.000000,1.0,1,...,0.800183,0.800183,0.800183,0.800183,0,0,0.984142,0.003537,0.000237,0.824970

In [3]:
result=map(lambda x: SRA1_EXT(x,I_0=0.01,σo=σo,σn=σn,δo=δo,δn=δn),m_vals)
result=list(result)
data=pd.DataFrame.from_records(result, columns =['func', '𝜋1','𝜋2','𝜋3','S4','I4','Ud'])
data['m']=m_vals
data=data.rename(columns={'func':'D_vals'})


data.to_csv('210407 SRA1 TimeExtMaskExp.csv',index=False)
data

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_TimeExt.py:216: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nR,nD]))

      D_vals        𝜋1        𝜋2        𝜋3        S4        I4        Ud     m
0   0.001829  0.100006  0.100016  0.100033  0.932612  0.043648  1.149997  0.10
1   0.001753  0.110007  0.110018  0.110035  0.934652  0.041974  1.144997  0.11
2   0.001680  0.120007  0.120019  0.120038  0.936620  0.040366  1.139996  0.12
3   0.001611  0.130008  0.130021  0.130041  0.938517  0.038820  1.134996  0.13
4   0.001544  0.140008  0.140022  0.140043  0.940346  0.037335  1.129996  0.14
..       ...       ...       ...       ...       ...       ...       ...   ...
66  0.000249  0.760046  0.760085  0.760114  0.984247  0.004869  0.819977  0.76
67  0.000245  0.770046  0.770085  0.770115  0.984438  0.004761  0.814977  0.77
68  0.000242  0.780047  0.780086  0.780115  0.984622  0.004658  0.809977  0.78
69  0.000238  0.790047  0.790087  0.790116  0.984800  0.004559  0.804976  0.79
70  0.000235  0.800048  0.800087  0.800117  0.984973  0.004464  0.799976  0.80

[71 rows x 8 columns]

In [4]:
result=map(lambda x: SRA2_EXT(x,I_0=0.01,σo=σo,σn=σn,δo=δo,δn=δn),m_vals)
result=list(result)
data=pd.DataFrame.from_records(result, columns =['func','𝜋1','𝜋20','𝜋21','𝜋30','𝜋31','𝜋32','S4','I4','Ud'])
data['m']=m_vals
data=data.rename(columns={'func':'D_vals'})


data.to_csv('210407 SRA2 TimeExtMaskExp.csv',index=False)
data

C:\Users\coolcold1898\Dropbox\COVID-19-Mask\要上傳的程式碼\code files\model_TimeExt.py:216: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return(np.array([nS,nI,nR,nD]))

,D_vals,𝜋1,𝜋20,𝜋21,𝜋30,𝜋31,𝜋32,S4,I4,Ud,m
0,0.001805,0.100006,0.111130,0.000000,0.125045,0.0,0.000000,0.932961,0.043298,1.149997,0.10
1,0.001724,0.110007,0.123616,0.000000,0.141077,0.0,0.000000,0.935061,0.041566,1.144997,0.11
2,0.001647,0.120007,0.136387,0.000000,0.157952,0.0,0.000000,0.937090,0.039896,1.139996,0.12
3,0.001574,0.130008,0.149450,0.000000,0.175739,0.0,0.000000,0.939049,0.038288,1.134996,0.13
4,0.001503,0.140008,0.162818,0.000000,0.194515,0.0,0.000000,0.940942,0.036739,1.129996,0.14
...,...,...,...,...,...,...,...,...,...,...,...
66,0.000242,0.760046,1.000000,0.684341,1.000000,1.0,0.538798,0.984446,0.004670,0.819977,0.76
67,0.000239,0.770046,1.000000,0.701428,1.000000,1.0,0.574391,0.984616,0.004583,0.814977,0.77
68,0.000236,0.780047,1.000000,0.718076,1.000000,1.0,0.607443,0.984781,0.004499,0.809977,0.78
69,0.000233,0.790047,1.000000,0.734303,1.000000,1.0,0.638215,0.984942,0.004418,0.804976,0.79
70,0.000231,0.800048,1.000000,0.750124,1.000000,1.0,0.666937,0.985098,0.004339,0.799976,0.80